version: "3.6"
services:
  node:
    image: too-many-cells-js:latest
    build: ./
    depends_on:
      - mongo
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017/tmc
      - MONGO_DB=tmc
    networks:
      - tmc-network
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - tmc-network

volumes:
  mongo-data:

networks:
  tmc-network: