version: "3.6"
services:
  react:
    image: node:latest
    volumes:
      - ./react:/usr/app
    working_dir: /usr/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - APP_PORT
      - NODE_PORT
    entrypoint: "yarn start"
  node:
    image: node:latest
    volumes:
      - ./node:/usr/app
    working_dir: /usr/app
    environment:
      - NODE_PORT
      - STATIC_DIR
    entrypoint: "yarn start"