version: "3.6"
services:
  node:
    image: too-many-cells-js:latest
    build: ./
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=tmc
    networks:
      - tmc-network
  postgres:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=tmc
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tmc-network

volumes:
  postgres-data:

networks:
  tmc-network:
